/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs_.$slug'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminServicesNewRouteImport } from './routes/admin/services_.new'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects_.new'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products_.new'
import { Route as AdminBlogsNewRouteImport } from './routes/admin/blogs_.new'
import { Route as AdminServicesIdEditRouteImport } from './routes/admin/services_.$id.edit'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin/projects_.$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products_.$id.edit'
import { Route as AdminBlogsIdEditRouteImport } from './routes/admin/blogs_.$id.edit'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs_/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesNewRoute = AdminServicesNewRouteImport.update({
  id: '/services_/new',
  path: '/services/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs_/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIdEditRoute = AdminServicesIdEditRouteImport.update({
  id: '/services_/$id/edit',
  path: '/services/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/projects_/$id/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products_/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIdEditRoute = AdminBlogsIdEditRouteImport.update({
  id: '/blogs_/$id/edit',
  path: '/blogs/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/services': typeof AdminServicesRoute
  '/blogs_/$slug': typeof BlogsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products_/$slug': typeof ProductsSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blogs_/new': typeof AdminBlogsNewRoute
  '/admin/products_/new': typeof AdminProductsNewRoute
  '/admin/projects_/new': typeof AdminProjectsNewRoute
  '/admin/services_/new': typeof AdminServicesNewRoute
  '/admin/blogs_/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/products_/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/projects_/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/services_/$id/edit': typeof AdminServicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/career'
    | '/contact'
    | '/products'
    | '/projects'
    | '/services'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/services'
    | '/blogs/$slug'
    | '/product/$slug'
    | '/products/$slug'
    | '/project/$slug'
    | '/service/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/admin/blogs/new'
    | '/admin/products/new'
    | '/admin/projects/new'
    | '/admin/services/new'
    | '/admin/blogs/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/services/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/career'
    | '/contact'
    | '/products'
    | '/projects'
    | '/services'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/services'
    | '/blogs/$slug'
    | '/product/$slug'
    | '/products/$slug'
    | '/project/$slug'
    | '/service/$slug'
    | '/services/$slug'
    | '/admin'
    | '/admin/blogs/new'
    | '/admin/products/new'
    | '/admin/projects/new'
    | '/admin/services/new'
    | '/admin/blogs/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/services/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/career'
    | '/contact'
    | '/products'
    | '/projects'
    | '/services'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/services'
    | '/blogs_/$slug'
    | '/product/$slug'
    | '/products_/$slug'
    | '/project/$slug'
    | '/service/$slug'
    | '/services_/$slug'
    | '/admin/'
    | '/admin/blogs_/new'
    | '/admin/products_/new'
    | '/admin/projects_/new'
    | '/admin/services_/new'
    | '/admin/blogs_/$id/edit'
    | '/admin/products_/$id/edit'
    | '/admin/projects_/$id/edit'
    | '/admin/services_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogsRoute: typeof BlogsRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs_/$slug': {
      id: '/blogs_/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services_/new': {
      id: '/admin/services_/new'
      path: '/services/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminServicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects_/new': {
      id: '/admin/projects_/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products_/new': {
      id: '/admin/products_/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs_/new': {
      id: '/admin/blogs_/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services_/$id/edit': {
      id: '/admin/services_/$id/edit'
      path: '/services/$id/edit'
      fullPath: '/admin/services/$id/edit'
      preLoaderRoute: typeof AdminServicesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects_/$id/edit': {
      id: '/admin/projects_/$id/edit'
      path: '/projects/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products_/$id/edit': {
      id: '/admin/products_/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs_/$id/edit': {
      id: '/admin/blogs_/$id/edit'
      path: '/blogs/$id/edit'
      fullPath: '/admin/blogs/$id/edit'
      preLoaderRoute: typeof AdminBlogsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminServicesNewRoute: typeof AdminServicesNewRoute
  AdminBlogsIdEditRoute: typeof AdminBlogsIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
  AdminServicesIdEditRoute: typeof AdminServicesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminServicesNewRoute: AdminServicesNewRoute,
  AdminBlogsIdEditRoute: AdminBlogsIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
  AdminServicesIdEditRoute: AdminServicesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogsRoute: BlogsRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
